In [1]:
#import numpy and create 1 D numpy array
import numpy as np
oneDArray = np.array([1,2,3,4,5])
print(oneDArray.ndim)

1


In [2]:
# create 2d array
twoDArray = np.array([[1,2,3],[4,5,6]])
print(twoDArray)
#find dimension using ndim
print(twoDArray.ndim)

[[1 2 3]
 [4 5 6]]
2


In [3]:
#create 3d array
threeDArray = np.array([[[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
print(threeDArray)
print(threeDArray.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
3


In [5]:
#index of numpy array
#if we provide only one index it will find out the whole list in that position for 
#2d and whole array in that position for 3d array
print(twoDArray[1])
print(threeDArray[1])

[4 5 6]
[[-1 -2 -3]
 [-4 -5 -6]]


In [7]:
#if we provide the second index it will find out the specific element in that position for 
#2d and the list in that position for 3d array
print(twoDArray[1,2])
print(threeDArray[1,1])
#to get specific element in that position for 3d array use all 3 index
print(threeDArray[1,1,2])

6
[-4 -5 -6]
-6


In [8]:
#find shape of array using shape
print(twoDArray.shape)
print(threeDArray.shape)

(2, 3)
(2, 2, 3)


In [9]:
#iterate over array
# if it is 1D array, iterate similar to a list
for i in oneDArray:
    print(i)

1
2
3
4
5


In [10]:
#if it is 2D array, you require nested loop
#outer loop is for outer array, inner loop is for inner array, if you iterate only once
#it will only 1D array element, you need to iterate again over these array elements to get specific
#elements
for i in twoDArray:
    print(i)
    for j in i:
        print(j)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [12]:
# iterating over 3d array is similar to 2D array,iterate only once you will get the 2 D array
#elements, if you iterate inside that , you will get 1D array elements, you need to iterate
#once more to get specific elements
for i in threeDArray:
    print(i)
    for j in i:
        print(j)
        for k in j:
            print(k)

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
2
3
[4 5 6]
4
5
6
[[-1 -2 -3]
 [-4 -5 -6]]
[-1 -2 -3]
-1
-2
-3
[-4 -5 -6]
-4
-5
-6
