In [1]:
#import numpy and create 1 D numpy array
import numpy as np
oneDArray = np.array([1,2,3,4,5])
print(oneDArray.ndim)

1


In [2]:
# create 2d array
twoDArray = np.array([[1,2,3],[4,5,6]])
print(twoDArray)
#find dimension using ndim
print(twoDArray.ndim)

[[1 2 3]
 [4 5 6]]
2


In [3]:
#create 3d array
threeDArray = np.array([[[1,2,3],[4,5,6]],[[-1,-2,-3],[-4,-5,-6]]])
print(threeDArray)
print(threeDArray.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
3


In [5]:
#index of numpy array
#if we provide only one index it will find out the whole list in that position for 
#2d and whole array in that position for 3d array
print(twoDArray[1])
print(threeDArray[1])

[4 5 6]
[[-1 -2 -3]
 [-4 -5 -6]]


In [7]:
#if we provide the second index it will find out the specific element in that position for 
#2d and the list in that position for 3d array
print(twoDArray[1,2])
print(threeDArray[1,1])
#to get specific element in that position for 3d array use all 3 index
print(threeDArray[1,1,2])

6
[-4 -5 -6]
-6


In [8]:
#find shape of array using shape
print(twoDArray.shape)
print(threeDArray.shape)

(2, 3)
(2, 2, 3)


In [9]:
#iterate over array
# if it is 1D array, iterate similar to a list
for i in oneDArray:
    print(i)

1
2
3
4
5


In [10]:
#if it is 2D array, you require nested loop
#outer loop is for outer array, inner loop is for inner array, if you iterate only once
#it will only 1D array element, you need to iterate again over these array elements to get specific
#elements
for i in twoDArray:
    print(i)
    for j in i:
        print(j)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [12]:
# iterating over 3d array is similar to 2D array,iterate only once you will get the 2 D array
#elements, if you iterate inside that , you will get 1D array elements, you need to iterate
#once more to get specific elements
for i in threeDArray:
    print(i)
    for j in i:
        print(j)
        for k in j:
            print(k)

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
2
3
[4 5 6]
4
5
6
[[-1 -2 -3]
 [-4 -5 -6]]
[-1 -2 -3]
-1
-2
-3
[-4 -5 -6]
-4
-5
-6


In [15]:
#linear spaced vector
# linspace() can be used to create linear space vector, where 1st argument gives starting 
#element, 2nd arg gives end element and 3rd arg gives step of change . Start and end element 
#gives direction of change whether it will increase or decrease
#example, start with 0, increment by 5, end by 20
vector = np.linspace(0,20,5)
print(vector)
#example, start with 20, decrease by 5, end by 0
vector2 = np.linspace(20,0,5)
print(vector2)

[ 0.  5. 10. 15. 20.]
[20. 15. 10.  5.  0.]


In [19]:
#reshape
# you can use reshape() to change linear array to a 3D array
# numpy allow creating array with element value 0, need to mention number of elements in
#argument
zeroLinearArray = np.zeros(8) 
print(zeroLinearArray)
#you can also mention shape, element type and order in argument
zeroLinearArray = np.zeros(8, dtype=int, order='C')
print(zeroLinearArray)
# based on which type of array you want to reshape into, mention the dimension
#keep in mind the element and dimension should match, for example here we are creating
#2 x 2 x 2 array, we need to have 8 elements
arr3D = zeroLinearArray.reshape((2,2,2))
print(arr3D)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0]
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [20]:
#ravel
# you can use ravel to flatten 3D array to linear array
arrFlat = arr3D.ravel()
print(arrFlat)

[0 0 0 0 0 0 0 0]


In [22]:
#slicing
#if you mention the first index, it will get element from that index upto last
#if you mention ending index, it will get element from first upto that index
arr = np.arange(20) # this will create an array from 0 to 20,
print(arr)
print(arr[2:]) #print all elements starting from index 2
print(arr[:15])#print all elements till index less than 15

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [35]:
# extract specific rows and columns
arr = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(arr)
# slice items starting from index
print (arr[1:])
# this returns array of items in the second column  
print (arr[:,1])
# Now we will slice all items from the second row 
print (arr[1,:])   
# Now we will slice all items from column 1 onwards 
print (arr[:,1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]
[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [31]:
#sort
# use np.sort() to sort array
arr = np.array([[1,3,2],[4,3,5],[4,5,1]])
print(np.sort(arr))

[[1 2 3]
 [3 4 5]
 [1 4 5]]


In [33]:
# if you need to sort on axis 0
arr = np.array([[1,3,2],[4,3,5],[4,5,1]])
print (np.sort(arr, axis = 0))
# if you need to sort on axis 1
arr = np.array([[1,3,2],[4,3,5],[4,5,1]])
print (np.sort(arr, axis = 1))

[[1 3 1]
 [4 3 2]
 [4 5 5]]
[[1 2 3]
 [3 4 5]
 [1 4 5]]


In [36]:
#delete
arr= np.arange(10,19)
print (arr)
#delete array based on index
arr= np.delete (arr, [2,5])
print (arr)

[10 11 12 13 14 15 16 17 18]
[10 11 13 14 16 17 18]
